// GENERATED by scripts/apply-keywords-v2.mjs from ../SEO Analysis/home.js (Semrush bank, KD <= 28) - do not edit by hand.
// primary = highest-volume Transactional keyword; primaries = next Transactional; secondary = 15; tags = the visible tags line (Commercial + Transactional, highest volume).
export const HOME_SEO = {
 "primary": {
  "kw": "glenfiddich",
  "vol": 14800,
  "kd": 27,
  "intent": "Transactional"
 },
 "primaries": [
  {
   "kw": "pinot grigio",
   "vol": 8100
  },
  {
   "kw": "corona beer",
   "vol": 8100
  },
  {
   "kw": "kraken rum",
   "vol": 8100
  },
  {
   "kw": "don julio",
   "vol": 8100
  },
  {
   "kw": "premix king",
   "vol": 5400
  }
 ],
 "secondary": [
  {
   "kw": "baileys irish cream",
   "vol": 6600
  },
  {
   "kw": "belvedere vodka",
   "vol": 6600
  },
  {
   "kw": "chandon brut",
   "vol": 6600
  },
  {
   "kw": "ouzo",
   "vol": 6600
  },
  {
   "kw": "tequila from tequila",
   "vol": 6600
  },
  {
   "kw": "beer ginger beer",
   "vol": 6600
  },
  {
   "kw": "jameson whisky",
   "vol": 6600
  },
  {
   "kw": "johnnie walker blue label",
   "vol": 6600
  },
  {
   "kw": "cruisers",
   "vol": 6600
  },
  {
   "kw": "rose wine",
   "vol": 6600
  },
  {
   "kw": "white wine",
   "vol": 6600
  },
  {
   "kw": "somersby",
   "vol": 6600
  },
  {
   "kw": "cognac cognac",
   "vol": 5400
  },
  {
   "kw": "smirnoff",
   "vol": 5400
  },
  {
   "kw": "don julioooo",
   "vol": 5400
  }
 ],
 "tags": [
  {
   "kw": "baileys",
   "vol": 22200
  },
  {
   "kw": "tequila",
   "vol": 22200
  },
  {
   "kw": "prosecco",
   "vol": 22200
  },
  {
   "kw": "jack daniels",
   "vol": 18100
  },
  {
   "kw": "champagne",
   "vol": 18100
  },
  {
   "kw": "whisky",
   "vol": 14800
  },
  {
   "kw": "veuve clicquot",
   "vol": 14800
  },
  {
   "kw": "gin",
   "vol": 14800
  },
  {
   "kw": "pepsi max",
   "vol": 14800
  },
  {
   "kw": "smirnoff vodka",
   "vol": 12100
  },
  {
   "kw": "cognac",
   "vol": 9900
  },
  {
   "kw": "jim beam",
   "vol": 9900
  },
  {
   "kw": "bourbon",
   "vol": 9900
  },
  {
   "kw": "kahlua",
   "vol": 9900
  },
  {
   "kw": "glenfiddich 12",
   "vol": 9900
  },
  {
   "kw": "red wine",
   "vol": 9900
  },
  {
   "kw": "scotch",
   "vol": 9900
  },
  {
   "kw": "moet",
   "vol": 8100
  },
  {
   "kw": "rum",
   "vol": 8100
  },
  {
   "kw": "absolut vodka",
   "vol": 8100
  },
  {
   "kw": "patron",
   "vol": 8100
  },
  {
   "kw": "sauvignon blanc",
   "vol": 8100
  },
  {
   "kw": "absolut liquor",
   "vol": 6600
  },
  {
   "kw": "pinot grigio",
   "vol": 8100
  },
  {
   "kw": "corona beer",
   "vol": 8100
  }
 ],
 "headline": [
  "whisky",
  "tequila",
  "gin"
 ]
};
