// GENERATED by scripts/apply-keywords-v2.mjs from the Whisky Keywords Bank (Semrush) - do not edit by hand.
export const HOME_SEO = {
 "primary": {
  "kw": "buy whisky online",
  "vol": 390,
  "kd": 28,
  "intent": "Transactional",
  "raw": "Transactional",
  "lvl": "page"
 },
 "secondary": [
  {
   "kw": "whiskey gifts australia",
   "vol": 1900
  },
  {
   "kw": "best whisky in australia",
   "vol": 590
  },
  {
   "kw": "best whiskey australia",
   "vol": 590
  },
  {
   "kw": "cheap whiskey australia",
   "vol": 320
  },
  {
   "kw": "cheapest whisky in australia",
   "vol": 320
  },
  {
   "kw": "rye whiskey australia",
   "vol": 320
  },
  {
   "kw": "cheap whisky australia",
   "vol": 260
  },
  {
   "kw": "best whiskey in australia",
   "vol": 260
  },
  {
   "kw": "best scotch whisky australia",
   "vol": 260
  },
  {
   "kw": "cheapest whiskey in australia",
   "vol": 260
  },
  {
   "kw": "bourbon australia",
   "vol": 260
  },
  {
   "kw": "cheap bourbon australia",
   "vol": 260
  },
  {
   "kw": "best irish whiskey australia",
   "vol": 260
  },
  {
   "kw": "single malt whisky australia",
   "vol": 210
  },
  {
   "kw": "best whisky australia",
   "vol": 210
  }
 ],
 "tags": [
  {
   "kw": "good whiskey australia",
   "vol": 210
  },
  {
   "kw": "best scotch australia",
   "vol": 210
  },
  {
   "kw": "whiskey brands australia",
   "vol": 170
  },
  {
   "kw": "single malt whiskey australia",
   "vol": 170
  },
  {
   "kw": "wild turkey bourbon australia",
   "vol": 170
  },
  {
   "kw": "bourbon whiskey australia",
   "vol": 140
  },
  {
   "kw": "best single malt whiskey australia",
   "vol": 140
  },
  {
   "kw": "best scotch in australia",
   "vol": 140
  },
  {
   "kw": "good scotch australia",
   "vol": 110
  },
  {
   "kw": "whisky gift pack australia",
   "vol": 110
  },
  {
   "kw": "best scotch whiskey australia",
   "vol": 110
  },
  {
   "kw": "japanese whisky australia",
   "vol": 110
  },
  {
   "kw": "whisky gifts australia",
   "vol": 110
  },
  {
   "kw": "bourbon in australia",
   "vol": 110
  },
  {
   "kw": "top 10 whisky in australia",
   "vol": 90
  },
  {
   "kw": "whisky in australia",
   "vol": 90
  },
  {
   "kw": "australia whisky brands",
   "vol": 90
  },
  {
   "kw": "whisky online order",
   "vol": 90
  },
  {
   "kw": "whisky subscription australia",
   "vol": 90
  },
  {
   "kw": "order bourbon online",
   "vol": 90
  },
  {
   "kw": "japanese whisky delivery",
   "vol": 70
  },
  {
   "kw": "scotch whisky australia",
   "vol": 70
  }
 ]
};
