// GENERATED by scripts/add-new-catalogue.mjs - collections added from the keyword bank (keyword strategy v2).
export const NEW_COLLECTION_LINKS: Record<string, { label: string; href: string }[]> = {
  "whisky": [
    {
      "label": "Irish Whiskey",
      "href": "/shop/whisky/collection/irish-whiskey"
    }
  ],
  "spirit": [
    {
      "label": "Vodka",
      "href": "/shop/spirit/collection/vodka"
    },
    {
      "label": "Rum",
      "href": "/shop/spirit/collection/rum"
    },
    {
      "label": "Liqueurs",
      "href": "/shop/spirit/collection/liqueur"
    },
    {
      "label": "Pink Gin",
      "href": "/shop/spirit/collection/pink-gin"
    },
    {
      "label": "Ouzo",
      "href": "/shop/spirit/collection/ouzo"
    }
  ],
  "beer-premix-wine": [
    {
      "label": "Champagne",
      "href": "/shop/beer-premix-wine/collection/champagne"
    },
    {
      "label": "Australian Beer",
      "href": "/shop/beer-premix-wine/collection/australian-beer"
    },
    {
      "label": "Prosecco",
      "href": "/shop/beer-premix-wine/collection/prosecco"
    },
    {
      "label": "Pinot Grigio",
      "href": "/shop/beer-premix-wine/collection/pinot-grigio"
    },
    {
      "label": "Sauvignon Blanc",
      "href": "/shop/beer-premix-wine/collection/sauvignon-blanc"
    },
    {
      "label": "Low Carb & Mid Strength Beer",
      "href": "/shop/beer-premix-wine/collection/low-carb-beer"
    },
    {
      "label": "Grenache",
      "href": "/shop/beer-premix-wine/collection/grenache"
    },
    {
      "label": "German Beer",
      "href": "/shop/beer-premix-wine/collection/german-beer"
    },
    {
      "label": "Cabernet Sauvignon",
      "href": "/shop/beer-premix-wine/collection/cabernet-sauvignon"
    },
    {
      "label": "Pilsner",
      "href": "/shop/beer-premix-wine/collection/pilsner"
    }
  ]
};
