// Maps source photo folders (in "pictures of whisky/") and keyword CSVs
// (in "Whisky Keywords Bank/") onto the site's subcategory pages.
//
// This taxonomy matches the exact subcategory/keyword list the client
// supplied for on-page SEO. Every entry below has real product photography
// and becomes a real, indexable /shop/[category]/collection/[slug] page.
//
// A handful of terms from the client's list have keyword-bank research but
// NO product photography available (Jägermeister, Kahlúa, Cointreau, Aperol,
// Grand Marnier, Disaronno, Campari, St Germain, Chartreuse, Dark Rum,
// Pale Ale, IPA, Gin Premix). Rather than publish empty/thin pages for terms
// with zero real inventory, their keyword data is folded into the closest
// real sibling subcategory below (see `keywordFiles` + `relatedInquiry`) so
// the terms still appear as genuine secondary keywords and on-page copy.
// "Rum Premix" has neither photos nor keyword-bank data and is not covered.

export const SUBCATEGORIES = [
  // ==================== WHISKY ====================
  {
    slug: 'scotch-whisky',
    name: 'Scotch Whisky',
    category: 'whisky',
    folders: ['Macallan', 'GlenDronach', 'Glenfiddich', 'Laphroaig', 'Royal Salute', 'Johnnie Walker'],
    keywordFiles: ['Scotch-Whisky', 'Single-Malt', 'Macallan', 'GlenDronach', 'Glenfiddich', 'Laphroaig', 'Royal-Salute', 'Johnnie-Walker'],
    primaryOverride: 'scotch whisky',
    country: 'Scotland',
    style: 'Single Malt / Blended Scotch',
    priceTier: [95, 4850],
  },
  {
    slug: 'bourbon',
    name: 'Bourbon Whiskey',
    category: 'whisky',
    folders: ['Bourbon'],
    keywordFiles: ['Bourbon', 'American-Whiskey'],
    country: 'United States',
    style: 'Bourbon',
    priceTier: [55, 650],
  },
  {
    slug: 'rye-whiskey',
    name: 'Rye Whiskey',
    category: 'whisky',
    folders: ['Rye Whiskey'],
    keywordFiles: ['Rye-Whiskey', 'American-Whiskey'],
    country: 'United States',
    style: 'Rye',
    priceTier: [60, 550],
  },
  {
    slug: 'japanese-whisky',
    name: 'Japanese Whisky',
    category: 'whisky',
    folders: ['Nikka'],
    keywordFiles: ['Japanese-Whisky'],
    country: 'Japan',
    style: 'Pure Malt / Blended',
    priceTier: [90, 1850],
  },
  {
    slug: 'australian-whisky',
    name: 'Australian Whisky',
    category: 'whisky',
    folders: ['Lark'],
    keywordFiles: ['Australian-Whisky'],
    country: 'Australia',
    style: 'Single Malt',
    priceTier: [120, 1990],
  },

  // ==================== SPIRIT — VODKA ====================
  {
    slug: 'french-vodka',
    name: 'French Vodka',
    category: 'spirit',
    folders: ['French Vodka'],
    keywordFiles: ['Vodka', 'Grey-Goose'],
    primaryOverride: 'french vodka',
    country: 'France',
    style: 'Vodka',
    priceTier: [50, 220],
  },
  {
    slug: 'russian-vodka',
    name: 'Russian Vodka',
    category: 'spirit',
    folders: ['Russian Vodka'],
    keywordFiles: ['Russian-Vodka', 'Vodka'],
    primaryHints: ['russian vodka'],
    country: 'Russia',
    style: 'Vodka',
    priceTier: [45, 180],
  },
  {
    slug: 'polish-vodka',
    name: 'Polish Vodka',
    category: 'spirit',
    folders: ['Polish Vodka'],
    keywordFiles: ['Polish-Vodka', 'Vodka'],
    primaryHints: ['polish vodka'],
    country: 'Poland',
    style: 'Vodka',
    priceTier: [45, 180],
  },
  {
    slug: 'grey-goose',
    name: 'Grey Goose',
    primaryOverride: 'grey goose',
    category: 'spirit',
    folders: ['Grey Goose'],
    keywordFiles: ['Grey-Goose', 'Vodka'],
    primaryHints: ['grey goose'],
    country: 'France',
    style: 'Ultra-Premium Vodka',
    priceTier: [60, 340],
  },
  {
    slug: 'belvedere',
    name: 'Belvedere',
    primaryOverride: 'belvedere',
    category: 'spirit',
    folders: ['Belvedere'],
    keywordFiles: ['Belvedere', 'Vodka'],
    primaryHints: ['belvedere'],
    country: 'Poland',
    style: 'Ultra-Premium Vodka',
    priceTier: [60, 340],
  },

  // ==================== SPIRIT — TEQUILA & MEZCAL ====================
  {
    slug: 'mezcal',
    name: 'Mezcal',
    category: 'spirit',
    folders: ['Mezcal'],
    keywordFiles: ['Mezcal'],
    country: 'Mexico',
    style: 'Mezcal',
    priceTier: [85, 320],
  },
  {
    slug: 'patron',
    name: 'Patrón',
    category: 'spirit',
    folders: ['Patron'],
    keywordFiles: ['Patron', 'Tequila'],
    primaryHints: ['patron', 'patrón'],
    country: 'Mexico',
    style: 'Tequila',
    priceTier: [70, 900],
  },
  {
    slug: 'don-julio',
    name: 'Don Julio',
    category: 'spirit',
    folders: ['Don Julio'],
    keywordFiles: ['Don-Julio', 'Tequila'],
    primaryHints: ['don julio'],
    country: 'Mexico',
    style: 'Tequila',
    priceTier: [70, 990],
  },
  {
    slug: 'jose-cuervo',
    name: 'Jose Cuervo',
    category: 'spirit',
    folders: ['Jose Cuervo'],
    keywordFiles: ['Jose-Cuervo', 'Tequila'],
    primaryHints: ['jose cuervo'],
    country: 'Mexico',
    style: 'Tequila',
    priceTier: [45, 250],
  },
  {
    slug: 'white-tequila',
    name: 'White Tequila',
    category: 'spirit',
    folders: ['White Tequila'],
    keywordFiles: ['White-Tequila', 'Tequila'],
    primaryHints: ['white tequila', 'blanco tequila', 'silver tequila'],
    country: 'Mexico',
    style: 'Blanco',
    priceTier: [45, 300],
  },
  {
    slug: 'gold-tequila',
    name: 'Gold Tequila',
    primaryOverride: 'gold tequila',
    category: 'spirit',
    folders: ['Gold Tequila'],
    keywordFiles: ['Gold-Tequila', 'Tequila'],
    primaryHints: ['gold tequila', 'reposado tequila'],
    country: 'Mexico',
    style: 'Reposado / Gold',
    priceTier: [45, 300],
  },

  // ==================== SPIRIT — RUM, GIN, BAIJIU, COGNAC ====================
  {
    slug: 'spiced-rum',
    name: 'Spiced Rum',
    category: 'spirit',
    // Dark Rum has real keyword-bank demand but no product photography —
    // folded in here so "dark rum" still surfaces as a genuine secondary
    // keyword and in on-page copy.
    folders: ['Spiced Rum'],
    keywordFiles: ['Spiced-Rum', 'Dark-Rum', 'Rum'],
    primaryHints: ['spiced rum'],
    relatedInquiry: ['Dark Rum'],
    country: 'Caribbean',
    style: 'Spiced Rum',
    priceTier: [40, 180],
  },
  {
    slug: 'white-rum',
    name: 'White Rum',
    primaryOverride: 'white rum',
    category: 'spirit',
    folders: ['White Rum'],
    keywordFiles: ['White-Rum', 'Rum'],
    primaryHints: ['white rum'],
    country: 'Caribbean',
    style: 'White Rum',
    priceTier: [40, 180],
  },
  {
    slug: 'gin',
    name: 'Gin',
    category: 'spirit',
    folders: ['Gin'],
    keywordFiles: ['Gin'],
    country: 'United Kingdom / Australia',
    style: 'London Dry / Contemporary',
    priceTier: [45, 180],
  },
  {
    slug: 'baijiu',
    name: 'Baijiu',
    category: 'spirit',
    folders: ['Baijiu'],
    keywordFiles: ['Baijiu'],
    country: 'China',
    style: 'Baijiu',
    priceTier: [90, 650],
  },
  {
    slug: 'cognac-brandy',
    name: 'Cognac & Brandy',
    category: 'spirit',
    folders: ['Martell', 'Cognac', 'Calvados'],
    keywordFiles: ['Cognac', 'Martell', 'Brandy', 'Calvados'],
    country: 'France',
    style: 'Cognac / Brandy',
    priceTier: [65, 2200],
  },

  // ==================== SPIRIT — LIQUEURS ====================
  {
    slug: 'baileys-irish-cream',
    name: 'Baileys Irish Cream',
    category: 'spirit',
    folders: ['Baileys Irish Cream'],
    keywordFiles: ['Baileys-Irish-Cream', 'Cream-Liqueur'],
    primaryHints: ['baileys'],
    country: 'Ireland',
    style: 'Cream Liqueur',
    priceTier: [30, 90],
  },
  {
    slug: 'coffee-liqueur',
    name: 'Coffee Liqueur',
    category: 'spirit',
    // Kahlúa has keyword-bank demand but no product photography — folded in.
    folders: ['Coffee Liqueur'],
    keywordFiles: ['Coffee-Liqueur', 'Kahlúa'],
    primaryHints: ['coffee liqueur'],
    relatedInquiry: ['Kahlúa'],
    country: 'International',
    style: 'Coffee Liqueur',
    priceTier: [30, 90],
  },
  {
    slug: 'orange-liqueur',
    name: 'Orange Liqueur',
    category: 'spirit',
    // Cointreau and Grand Marnier are both classic orange liqueurs with real
    // keyword-bank demand but no product photography — folded in.
    folders: ['Orange Liqueur'],
    keywordFiles: ['Orange-Liqueur', 'Cointreau', 'Grand-Marnier'],
    primaryHints: ['orange liqueur'],
    relatedInquiry: ['Cointreau', 'Grand Marnier'],
    country: 'International',
    style: 'Orange Liqueur',
    priceTier: [30, 110],
  },
  {
    slug: 'cinnamon-liqueur',
    name: 'Cinnamon Liqueur',
    category: 'spirit',
    folders: ['Cinnamon Liqueur'],
    keywordFiles: ['Cinnamon-Liqueur'],
    primaryHints: ['cinnamon liqueur', 'fireball'],
    country: 'International',
    style: 'Cinnamon Liqueur',
    priceTier: [25, 80],
  },
  {
    slug: 'amaro',
    name: 'Amaro',
    primaryOverride: 'amaro',
    category: 'spirit',
    // Campari, Aperol, Chartreuse, Jägermeister and Disaronno are all bitter
    // / herbal aperitif liqueurs with real keyword-bank demand but no
    // product photography — folded in here as the closest thematic match.
    folders: ['Amaro'],
    keywordFiles: ['Amaro', 'Campari', 'Aperol', 'Chartreuse', 'Jägermeister', 'Disaronno'],
    primaryHints: ['amaro'],
    relatedInquiry: ['Campari', 'Aperol', 'Chartreuse', 'Jägermeister', 'Disaronno'],
    country: 'Italy',
    style: 'Amaro / Herbal Liqueur',
    priceTier: [35, 140],
  },
  {
    slug: 'absinthe',
    name: 'Absinthe',
    primaryOverride: 'absinthe',
    category: 'spirit',
    folders: ['Absinthe'],
    keywordFiles: ['Absinthe'],
    country: 'France / Switzerland',
    style: 'Absinthe',
    priceTier: [40, 150],
  },
  {
    slug: 'limoncello',
    name: 'Limoncello',
    primaryOverride: 'limoncello',
    category: 'spirit',
    // St Germain (elderflower liqueur) has real keyword-bank demand but no
    // product photography — folded in as the closest light/floral match.
    folders: ['Limoncello'],
    keywordFiles: ['Limoncello', 'St-Germain'],
    primaryHints: ['limoncello'],
    relatedInquiry: ['St Germain'],
    country: 'Italy',
    style: 'Citrus Liqueur',
    priceTier: [25, 90],
  },
  {
    slug: 'sambuca',
    name: 'Sambuca',
    category: 'spirit',
    folders: ['Sambuca'],
    keywordFiles: ['Sambuca'],
    country: 'Italy',
    style: 'Anise Liqueur',
    priceTier: [25, 80],
  },

  // ==================== OTHER — SOJU ====================
  {
    slug: 'soju',
    name: 'Soju',
    category: 'other',
    folders: ['Soju'],
    keywordFiles: ['Soju'],
    country: 'South Korea',
    style: 'Soju',
    priceTier: [20, 65],
  },

  // ==================== BEER / PREMIX / WINE — BEER ====================
  {
    slug: 'lager',
    name: 'Lager',
    primaryOverride: 'lager',
    category: 'beer-premix-wine',
    // Pale Ale has real keyword-bank demand but no product photography.
    folders: ['Lager'],
    keywordFiles: ['Lager', 'Pale-Ale', 'Beer'],
    primaryHints: ['lager'],
    relatedInquiry: ['Pale Ale'],
    country: 'International',
    style: 'Lager',
    priceTier: [18, 65],
  },
  {
    slug: 'imported-beer',
    name: 'Imported Beer',
    category: 'beer-premix-wine',
    // IPA has real keyword-bank demand but no product photography.
    folders: ['Imported Beer'],
    keywordFiles: ['Imported-Beer', 'IPA', 'Beer'],
    primaryHints: ['imported beer'],
    relatedInquiry: ['IPA'],
    country: 'International',
    style: 'Imported',
    priceTier: [20, 75],
  },
  {
    slug: 'non-alcoholic-beer',
    name: 'Non-Alcoholic Beer',
    category: 'beer-premix-wine',
    folders: ['Non Alcoholic Beer'],
    keywordFiles: ['Non-Alcoholic', 'Light-Beer'],
    country: 'International',
    style: 'Non-Alcoholic',
    priceTier: [18, 55],
  },
  {
    slug: 'ginger-beer',
    name: 'Ginger Beer',
    category: 'beer-premix-wine',
    folders: ['Ginger Beer'],
    keywordFiles: ['Ginger-Beer'],
    primaryOverride: 'ginger beer',
    country: 'Australia',
    style: 'Ginger Beer',
    priceTier: [10, 40],
  },

  // ==================== BEER / PREMIX / WINE — WINE ====================
  {
    slug: 'red-wine',
    name: 'Red Wine',
    category: 'beer-premix-wine',
    folders: ['Red Wine'],
    keywordFiles: ['Red-Wine', 'Wine'],
    primaryHints: ['red wine', 'shiraz', 'cabernet', 'merlot', 'pinot noir'],
    country: 'Australia',
    style: 'Red Wine',
    priceTier: [25, 950],
  },
  {
    slug: 'white-wine',
    name: 'White Wine',
    category: 'beer-premix-wine',
    folders: ['White Wine'],
    keywordFiles: ['White-Wine', 'Wine'],
    primaryHints: ['white wine', 'chardonnay', 'sauvignon blanc', 'riesling', 'pinot gris'],
    country: 'Australia',
    style: 'White Wine',
    priceTier: [22, 320],
  },
  {
    slug: 'rose-wine',
    name: 'Rosé Wine',
    category: 'beer-premix-wine',
    folders: ['Rose Wine'],
    keywordFiles: ['Wine'],
    primaryHints: ['rose wine', 'rosé', 'rose'],
    primaryOverride: 'rose wine',
    country: 'France / Australia',
    style: 'Rosé',
    priceTier: [24, 280],
  },
  {
    slug: 'sparkling',
    name: 'Sparkling Wine',
    category: 'beer-premix-wine',
    folders: ['Sparkling'],
    keywordFiles: ['Sparkling', 'Wine'],
    primaryHints: ['sparkling wine', 'champagne', 'prosecco'],
    primaryOverride: 'sparkling wine',
    country: 'France / Australia',
    style: 'Sparkling',
    priceTier: [28, 1200],
  },
  {
    slug: 'port-wine',
    name: 'Port',
    category: 'beer-premix-wine',
    folders: ['Port Wine'],
    keywordFiles: ['Wine'],
    primaryHints: ['port wine', 'port'],
    primaryOverride: 'port wine',
    country: 'Portugal',
    style: 'Fortified',
    priceTier: [30, 500],
  },

  // ==================== BEER / PREMIX / WINE — PREMIX ====================
  {
    slug: 'vodka-premix',
    name: 'Vodka Premix',
    category: 'beer-premix-wine',
    // Gin Premix has real keyword-bank demand but no dedicated product
    // photography of its own — folded in here. "Rum Premix" has neither
    // keyword-bank data nor photography and isn't covered anywhere.
    folders: ['Vodka Premix'],
    keywordFiles: ['Vodka-Premix', 'Gin-Premix', 'Premix'],
    primaryHints: ['vodka premix'],
    relatedInquiry: ['Gin Premix'],
    country: 'Australia',
    style: 'Ready-to-Drink Premix',
    priceTier: [20, 70],
  },
  {
    slug: 'zero-sugar-seltzers',
    name: 'Zero Sugar',
    category: 'beer-premix-wine',
    folders: ['Zero Sugar'],
    keywordFiles: ['Zero-Sugar', 'Premix', 'Light-Beer'],
    primaryOverride: 'zero sugar',
    country: 'Australia',
    style: 'Seltzer',
    priceTier: [18, 55],
  },
  {
    slug: 'cider',
    name: 'Cider',
    category: 'beer-premix-wine',
    folders: ['Cider'],
    keywordFiles: ['Cider'],
    primaryHints: ['cider'],
    country: 'Australia',
    style: 'Cider',
    priceTier: [20, 65],
  },

  // ==================== OTHER — MIXERS ====================
  {
    slug: 'mixers-water-condiments',
    name: 'Mixers, Water & Condiments',
    category: 'other',
    folders: ['Water', 'Energy Drinks', 'Condiments'],
    keywordFiles: ['Water', 'energy-drink', 'Condiments'],
    country: 'International',
    style: 'Mixer / Condiment',
    priceTier: [8, 45],
  },
];

export const CATEGORY_META = {
  whisky: {
    name: 'WHISKY',
    slug: 'whisky',
    description: "Australia's most prestigious collection of rare single malts, aged Japanese whiskies, and limited distillery releases.",
  },
  spirit: {
    name: 'SPIRIT',
    slug: 'spirit',
    description: 'Rare Cognac decanters, artisanal tequilas, ultra-pure vodkas, and monastery herbal liqueurs.',
  },
  'beer-premix-wine': {
    name: 'BEER / PREMIX / WINE',
    slug: 'beer-premix-wine',
    description: 'Heritage Australian icon wines, vintage sparkling, craft beer, and luxury premixes.',
  },
  other: {
    name: 'OTHER',
    slug: 'other',
    description: 'Collector glassware, Korean heritage soju, artisan mixers, and rare condiments.',
  },
};
