// Maps source photo folders (in "pictures of whisky/") and keyword CSVs
// (in "Whisky Keywords Bank/") onto the site's ~26 topical subcategories.

export const SUBCATEGORIES = [
  // ---------------- WHISKY ----------------
  {
    slug: 'scotch-whisky',
    name: 'Scotch Whisky',
    category: 'whisky',
    folders: ['Macallan', 'GlenDronach', 'Glenfiddich', 'Laphroaig', 'Royal Salute', 'Johnnie Walker'],
    keywordFiles: ['Scotch-Whisky', 'Single-Malt', 'Macallan', 'GlenDronach', 'Glenfiddich', 'Laphroaig', 'Royal-Salute', 'Johnnie-Walker'],
    primaryOverride: 'scotch whisky',
    country: 'Scotland',
    style: 'Single Malt / Blended Scotch',
    priceTier: [95, 4850],
  },
  {
    slug: 'bourbon',
    name: 'Bourbon Whiskey',
    category: 'whisky',
    folders: ['Bourbon'],
    keywordFiles: ['Bourbon', 'American-Whiskey'],
    country: 'United States',
    style: 'Bourbon',
    priceTier: [55, 650],
  },
  {
    slug: 'rye-whiskey',
    name: 'Rye Whiskey',
    category: 'whisky',
    folders: ['Rye Whiskey'],
    keywordFiles: ['Rye-Whiskey', 'American-Whiskey'],
    country: 'United States',
    style: 'Rye',
    priceTier: [60, 550],
  },
  {
    slug: 'japanese-whisky',
    name: 'Japanese Whisky',
    category: 'whisky',
    folders: ['Nikka'],
    keywordFiles: ['Japanese-Whisky'],
    country: 'Japan',
    style: 'Pure Malt / Blended',
    priceTier: [90, 1850],
  },
  {
    slug: 'australian-whisky',
    name: 'Australian Whisky',
    category: 'whisky',
    folders: ['Lark'],
    keywordFiles: ['Australian-Whisky'],
    country: 'Australia',
    style: 'Single Malt',
    priceTier: [120, 1990],
  },

  // ---------------- SPIRIT ----------------
  {
    slug: 'vodka',
    name: 'Premium Vodka',
    category: 'spirit',
    folders: ['French Vodka', 'Polish Vodka', 'Russian Vodka', 'Belvedere', 'Grey Goose'],
    keywordFiles: ['Vodka', 'Grey-Goose', 'Belvedere', 'Polish-Vodka', 'Russian-Vodka'],
    country: 'France / Poland / Russia',
    style: 'Vodka',
    priceTier: [45, 250],
  },
  {
    slug: 'tequila',
    name: 'Tequila',
    category: 'spirit',
    folders: ['Don Julio', 'Jose Cuervo', 'Patron', 'Gold Tequila', 'White Tequila'],
    keywordFiles: ['Tequila', 'Don-Julio', 'Jose-Cuervo', 'Patron', 'Gold-Tequila', 'White-Tequila'],
    country: 'Mexico',
    style: 'Blanco / Reposado / Añejo',
    priceTier: [55, 990],
  },
  {
    slug: 'mezcal',
    name: 'Mezcal',
    category: 'spirit',
    folders: ['Mezcal'],
    keywordFiles: ['Mezcal'],
    country: 'Mexico',
    style: 'Mezcal',
    priceTier: [85, 320],
  },
  {
    slug: 'cognac-brandy',
    name: 'Cognac & Brandy',
    category: 'spirit',
    folders: ['Martell', 'Cognac', 'Calvados'],
    keywordFiles: ['Cognac', 'Martell', 'Brandy', 'Calvados'],
    country: 'France',
    style: 'Cognac / Brandy',
    priceTier: [65, 2200],
  },
  {
    slug: 'gin',
    name: 'Gin',
    category: 'spirit',
    folders: ['Gin'],
    keywordFiles: ['Gin', 'Gin-Premix'],
    country: 'United Kingdom / Australia',
    style: 'London Dry / Contemporary',
    priceTier: [45, 180],
  },
  {
    slug: 'rum',
    name: 'Rum',
    category: 'spirit',
    folders: ['White Rum', 'Spiced Rum'],
    keywordFiles: ['Dark-Rum', 'Rum'],
    country: 'Caribbean',
    style: 'White / Spiced / Dark',
    priceTier: [40, 220],
  },
  {
    slug: 'baijiu',
    name: 'Baijiu',
    category: 'spirit',
    folders: ['Baijiu'],
    keywordFiles: ['Baijiu'],
    country: 'China',
    style: 'Baijiu',
    priceTier: [90, 650],
  },
  {
    slug: 'italian-liqueurs',
    name: 'Italian Liqueurs & Aperitifs',
    category: 'spirit',
    folders: ['Amaro', 'Sambuca', 'Limoncello'],
    keywordFiles: ['Amaro', 'Sambuca', 'Limoncello', 'Campari', 'Aperol'],
    primaryHints: ['amaro', 'limoncello', 'sambuca', 'italian liqueur'],
    country: 'Italy',
    style: 'Amaro / Liqueur',
    priceTier: [35, 140],
  },
  {
    slug: 'flavoured-cream-liqueurs',
    name: 'Flavoured & Cream Liqueurs',
    category: 'spirit',
    folders: ['Orange Liqueur', 'Cinnamon Liqueur', 'Coffee Liqueur', 'Baileys Irish Cream'],
    keywordFiles: ['Orange-Liqueur', 'Cinnamon-Liqueur', 'Coffee-Liqueur', 'Baileys-Irish-Cream', 'Cream-Liqueur', 'Cointreau', 'Grand-Marnier', 'Kahlúa', 'Disaronno'],
    country: 'International',
    style: 'Liqueur',
    priceTier: [30, 120],
  },
  {
    slug: 'soju',
    name: 'Soju',
    category: 'other',
    folders: ['Soju'],
    keywordFiles: ['Soju'],
    country: 'South Korea',
    style: 'Soju',
    priceTier: [20, 65],
  },

  // ---------------- BEER / PREMIX / WINE ----------------
  {
    slug: 'craft-imported-beer',
    name: 'Craft & Imported Beer',
    category: 'beer-premix-wine',
    folders: ['Lager', 'Imported Beer'],
    keywordFiles: ['Lager', 'Imported-Beer', 'Beer', 'IPA', 'Pale-Ale'],
    country: 'International',
    style: 'Lager / Imported',
    priceTier: [18, 75],
  },
  {
    slug: 'non-alcoholic-beer',
    name: 'Non-Alcoholic Beer',
    category: 'beer-premix-wine',
    folders: ['Non Alcoholic Beer'],
    keywordFiles: ['Non-Alcoholic', 'Light-Beer'],
    country: 'International',
    style: 'Non-Alcoholic',
    priceTier: [18, 55],
  },
  {
    slug: 'cider',
    name: 'Cider',
    category: 'beer-premix-wine',
    folders: ['Cider'],
    keywordFiles: ['Cider'],
    primaryHints: ['cider'],
    country: 'Australia',
    style: 'Cider',
    priceTier: [20, 65],
  },
  {
    slug: 'red-wine',
    name: 'Red Wine',
    category: 'beer-premix-wine',
    folders: ['Red Wine'],
    keywordFiles: ['Red-Wine', 'Wine'],
    primaryHints: ['red wine', 'shiraz', 'cabernet', 'merlot', 'pinot noir'],
    country: 'Australia',
    style: 'Red Wine',
    priceTier: [25, 950],
  },
  {
    slug: 'white-wine',
    name: 'White Wine',
    category: 'beer-premix-wine',
    folders: ['White Wine'],
    keywordFiles: ['White-Wine', 'Wine'],
    primaryHints: ['white wine', 'chardonnay', 'sauvignon blanc', 'riesling', 'pinot gris'],
    country: 'Australia',
    style: 'White Wine',
    priceTier: [22, 320],
  },
  {
    slug: 'rose-wine',
    name: 'Rosé Wine',
    category: 'beer-premix-wine',
    folders: ['Rose Wine'],
    keywordFiles: ['Wine'],
    primaryHints: ['rose wine', 'rosé', 'rose'],
    primaryOverride: 'rose wine',
    country: 'France / Australia',
    style: 'Rosé',
    priceTier: [24, 280],
  },
  {
    slug: 'sparkling-fortified-wine',
    name: 'Sparkling & Fortified Wine',
    category: 'beer-premix-wine',
    folders: ['Sparkling', 'Port Wine'],
    keywordFiles: ['Sparkling', 'Wine'],
    primaryHints: ['sparkling', 'champagne', 'prosecco', 'port wine', 'port'],
    country: 'France / Portugal / Australia',
    style: 'Sparkling / Port',
    priceTier: [28, 1200],
  },
  {
    slug: 'vodka-gin-premix',
    name: 'Vodka & Gin Premix',
    category: 'beer-premix-wine',
    folders: ['Vodka Premix'],
    keywordFiles: ['Vodka-Premix', 'Gin-Premix', 'Premix'],
    country: 'Australia',
    style: 'Ready-to-Drink Premix',
    priceTier: [20, 70],
  },
  {
    slug: 'zero-sugar-seltzers',
    name: 'Zero Sugar Seltzers',
    category: 'beer-premix-wine',
    folders: ['Zero Sugar'],
    keywordFiles: ['Zero-Sugar', 'Premix', 'Vodka-Premix', 'Light-Beer'],
    primaryOverride: 'zero sugar',
    country: 'Australia',
    style: 'Seltzer',
    priceTier: [18, 55],
  },

  // ---------------- OTHER ----------------
  {
    slug: 'mixers-water-condiments',
    name: 'Mixers, Water & Condiments',
    category: 'other',
    folders: ['Ginger Beer', 'Water', 'Energy Drinks', 'Condiments'],
    keywordFiles: ['Ginger-Beer', 'Water', 'energy-drink', 'Condiments'],
    country: 'International',
    style: 'Mixer / Condiment',
    priceTier: [8, 45],
  },
];

export const CATEGORY_META = {
  whisky: {
    name: 'WHISKY',
    slug: 'whisky',
    description: "Australia's most prestigious collection of rare single malts, aged Japanese whiskies, and limited distillery releases.",
  },
  spirit: {
    name: 'SPIRIT',
    slug: 'spirit',
    description: 'Rare Cognac decanters, artisanal tequilas, ultra-pure vodkas, and monastery herbal liqueurs.',
  },
  'beer-premix-wine': {
    name: 'BEER / PREMIX / WINE',
    slug: 'beer-premix-wine',
    description: 'Heritage Australian icon wines, vintage sparkling, craft beer, and luxury premixes.',
  },
  other: {
    name: 'OTHER',
    slug: 'other',
    description: 'Collector glassware, Korean heritage soju, artisan mixers, and rare condiments.',
  },
};
